### ISSUE TITLE
Add field comments

### ISSUE THREAD

**Issue by ImUrX** [cyqsimon/documented#1]
Hello, I want to use this to have comments on a toml with serde, and I like suffering.

Would you like for me to PR here if I end up making it happen?

**Comment by cyqsimon** [comment]
Yes features are of course welcomed. But I wonder how you plan to implement this 🤔.

My initial thoughts were to derive an associated function on the enum, but that would require the user to have a variant constructed, which might not always be possible or practical. Plus, there already is [enum_assoc](https://docs.rs/enum-assoc/latest/enum_assoc/).

The "better" way from the UX perspective is to use associated constants, but AFAIK there is no good "rusty" way to associate a constant with each enum variant. Maybe some of what [strum](https://docs.rs/strum/latest/strum/#derives) is doing is worth looking into and/or referencing, but honestly none of them look too appealing to me.

Anyways I'll stop my rambling. What do you think?

**Comment by ImUrX** [comment]
My current plan is to map each comment to an array, and then have a way to look up the field from the struct to the array index (I was thinking of a phf map or a const array of tuples). I guess this is good enough for an start, but yeah it could be improved much further

**Comment by ImUrX** [comment]
By the way I DMed you on discord if you want to discuss this further in a more chatty way
